general:
  botID: 3378742327
  groupID: 758633338
  admin:
    - 3337913379

command:
  # 群内获取服务器人数设置
  getPlayers:
    trigger: '#ls'
    # 服务器别称，会将bungeecord中的服务器名替换
    # 若您使用的是bukkit，请无视
    server-nick:
      lobby: '登陆服'
      main: '主服'
      island: '空岛'
    # 回复格式，夹在 ** ** 中的文字会在在线人数为0时去除
    format: '在线: %online%**, 玩家: %players%**'

  # MCQQ绑定设置
  bind:
    trigger: '#绑定'

  # 群内运行命令设置
  execute:
    trigger: '/'
    # 是否加上执行命令花费的时间
    time-spent: false

  chat:
    mc2qq:
      trigger: '#'
      format: '[MC]%name%: %message%'
    qq2mc:
      trigger: ''
      format: '&7[&eQQ&7] &r%name%&7: &r%message%'
